### ISSUE TITLE
While running in ios i am getting this issue

### ISSUE THREAD

**Issue by sri-nayak** [ko-devHong/react-native-mqtt#1]
!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `CocoaMQTT` depends upon `MqttCocoaAsyncSocket`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

**Comment by ko-devHong** [comment]
@sri-nayak  Hello, I saw your reply and PR document well but I already wrote to install CocoaMQTT in Dependency. What is the problem? I don't know the difference from my existing code.

**Comment by sri-nayak** [comment]
@ko-devHong Hii, so when i am using this library with expo react native it asking to to add the code to install the cocomq in project direcotry .
and my project version are
Expo => 51.0.8
react-native 0.74.2
Node => 20

**Comment by ko-devHong** [comment]
@sri-nayak Yes, I've tried declaring modular_headers in podspec files, but I don't support it properly at the moment, so I want you to install it directly into the project podfile that uses this library.

**Comment by ko-devHong** [comment]
@sri-nayak  
This is the document I looked for, and I tried to apply the solution, but it didn't work.

1. https://github.com/CocoaPods/CocoaPods/issues/7683
2. https://github.com/CocoaPods/CocoaPods/issues/7598
3. https://stackoverflow.com/questions/74296853/how-to-set-module-headers-in-podspec-dependency

**Comment by sri-nayak** [comment]
Ook issue resolved thank u for the reference. u can decline the PR Request and again thank u.
i have few doubts
I am not able to confugre the topic name and queue name in mqtt could u help with this.
and thank u for the library .

**Comment by ko-devHong** [comment]
@sri-nayak   Why do we need a queue name? The name of the queue is not important. Please refer to the following instructions for the name of the topic 
https://github.com/ko-devHong/react-native-mqtt?tab=readme-ov-file#subscribe 

OR You can run the example file that I created. 

<img width="522" alt="스크린샷 2024-07-08 오후 4 17 51" src="https://github.com/ko-devHong/react-native-mqtt/assets/45538347/13670bbc-447b-4977-b972-1ed12bdc1564">

<img width="496" alt="스크린샷 2024-07-08 오후 4 18 20" src="https://github.com/ko-devHong/react-native-mqtt/assets/45538347/9fe2bf06-4265-4812-9522-7b9c0a59dd44">

**Comment by sri-nayak** [comment]
And I want to persist the connection even after closing the application the connection should persist until uninstall of application could u help with this

**Comment by ko-devHong** [comment]
@sri-nayak  Use global variables.  ex) redux, react-query
